# Generated by Django 4.2.6 on 2023-11-14 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('In process', 'In Process'), ('Done', 'Done')], default='Pending', max_length=15)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('start_position_latitude', models.CharField(max_length=254)),
                ('start_position_longitude', models.CharField(max_length=254)),
                ('end_position_latitude', models.CharField(blank=True, max_length=254, null=True)),
                ('end_position_longitude', models.CharField(blank=True, max_length=254, null=True)),
                ('additional_info', models.TextField()),
                ('date_accepted_rejected', models.DateTimeField(blank=True, null=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('paramedic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
