# Generated by Django 4.2.6 on 2023-11-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_paramedic_last_lat_lng_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositor',
            name='channel_name',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paramedic',
            name='channel_name',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
