# Generated by Django 4.2.6 on 2023-11-26 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_alter_dispositor_user_alter_paramedic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='paramedic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.paramedic'),
        ),
    ]
