# Generated by Django 4.2.6 on 2023-11-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_alter_emergencyalert_paramedic'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='route_geometry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
