# Generated by Django 4.2.6 on 2023-11-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_emergencyalert_route_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramedic',
            name='gps_accuracy',
            field=models.FloatField(default=0),
        ),
    ]
