# Generated by Django 4.2.6 on 2023-11-30 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_emergencyalert_route_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamedicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_profile', models.CharField(default='driving_car', max_length=30)),
                ('isochrone_range', models.IntegerField(default=120)),
                ('paramedic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_app.paramedic')),
            ],
        ),
    ]
