# Generated by Django 4.2.6 on 2023-11-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_paramedicsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramedicsettings',
            name='routing_profile',
            field=models.CharField(choices=[('driving_car', 'Poruszanie samochodem'), ('foot-walking', 'Poruszanie pieszo'), ('cycling-regular', 'Poruszanie rowerem')], default='driving_car', max_length=30),
        ),
    ]
