# Generated by Django 4.2.6 on 2023-12-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_alter_paramedicsettings_routing_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_latitude', models.CharField(max_length=254)),
                ('default_longitude', models.CharField(max_length=254)),
                ('default_zoom', models.IntegerField(default=12)),
            ],
        ),
    ]
