# Generated by Django 4.2.6 on 2023-12-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='default_latitude',
            field=models.CharField(default='51.1104', max_length=254),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_longitude',
            field=models.CharField(default='17.0317', max_length=254),
        ),
    ]
